---
title: "Methods"
output: html_document2
---

## Data

The dataset used in this project were obtained from a series of speed dating studies led by Dr. Ray Fisman and Dr. Sheena Iyengar conducted between 2002 and 2004 at Columbia University [@fisman2006gender]. Data were collected across 21 different sessions (known as “waves” in the dataset). Data was sourced from OpenML [@vanschoren2014openml] and can be found [here](http://www.stat.columbia.edu/~gelman/arm/examples/speed.dating/).

In the experiment, men and women went on a speed dating rotation where they interacted and subsequently rated each other on 6 attributes: attractive, sincere, intelligent, fun, ambitious, and shared interest/hobbies. Critically, they were also asked to report whether they would see this person again or not. In addition to rating the other party, each participant also rated themselves on 5 of the 6 attributes (attractive, sincere, intelligent, fun, ambitious). Specifically, they were asked to rate how they measured up to each attribute, as well as how they thought others perceived them.

An observation or row in the data represents one set of ratings per ratee. For instance, if an individual saw 10 different partners in the session, then that individual would make 10 different ratings, one for each partner they interacted with at the event.


## Analysis

We conducted a one-sample t-test in order to examine our core research question of interest (i.e., whether self-perception of attractiveness is accurate). That is, we would take the difference in self- vs other-rated attractiveness and compare it against zero; if our difference score is statistically different from zero, then we would have sufficient evidence to reject the null hypothesis (i.e., that there is no difference between self- vs other-rated attractiveness). 

### Data Pre-Processing

Since observations in the original raw dataset violated assumptions of independence (i.e., each rater made multiple ratings and each ratee received multiple ratings), we decided to first process the data by averaging how each rater rated the attractiveness of each ratee. 

We then calculated a difference score by subtracting how others perceived an individual’s attractiveness from an individual’s rating of their own perceived attractiveness by others (i.e., own perception – other perception). As such, a positive score indicates that an individual was overly confident in their own perceived attractiveness.

Analysis and graphs were produced using the R programming language [@r_core_team_r_2019] as well as the following R packages: tidyverse [@wickham_welcome_2019], knitr [@xie_knitr_2023]. For the full code used to produce this report and analyses, please see: https://github.com/wenyunie/speed_dating_analysis.



